Import("env")

env.Append(CPPDEFINES=[
  ("WIFI_SSID", "YOUR WIFI SSID"),
	("WIFI_PASSWORD", "YOUR WIFI PASSWORD"),
	("WALLET_PASSPHRASE", "YOUR WALLET PASSPHRASE"),
  ("WALLET_ADDRESS", "DPKAyxsa7s9K3kQ5av8wwn9JY9a5ezxh4g")
])